apiVersion: v1
kind: Namespace
metadata:
  name: qualys-sensor
---
apiVersion: v1
kind: Secret
metadata:
  name: qualys-credentials
  namespace: qualys-sensor
type: Opaque
stringData:
  activation-id: "YOUR_ACTIVATION_ID"
  customer-id: "YOUR_CUSTOMER_ID"
  pod-url: "https://qualysapi.qualys.com"
